name: Build and Push Image, Test

on: [push]

# instead of running steps in the build server
# ci should push docker image to ECR and subsequent steps should pull image and run
# commands inside container

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python3 -m pip install -r requirements.txt
      - name: Lint
        run: |
          python3 -m pip install -r requirements_lint.txt
          black --check src/
          isort --check-only src/
      - name: Test
        run: |
          pytest